# Generated by Django 3.0.2 on 2020-08-25 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='location',
        ),
        migrations.AddField(
            model_name='user',
            name='actual_position',
            field=models.CharField(blank=True, max_length=50, verbose_name='actual_position'),
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, max_length=200, verbose_name='city'),
        ),
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(blank=True, max_length=200, verbose_name='country'),
        ),
        migrations.AddField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='date of birth'),
        ),
        migrations.AddField(
            model_name='user',
            name='github_profile',
            field=models.URLField(blank=True, verbose_name='github profile'),
        ),
        migrations.AddField(
            model_name='user',
            name='linkedin_profile',
            field=models.URLField(blank=True, verbose_name='linkedin profile'),
        ),
        migrations.AddField(
            model_name='user',
            name='nationality',
            field=models.CharField(blank=True, max_length=32, verbose_name='nationality'),
        ),
        migrations.AddField(
            model_name='user',
            name='permit',
            field=models.CharField(blank=True, max_length=32, verbose_name='permit'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=16, verbose_name='phone'),
        ),
        migrations.AddField(
            model_name='user',
            name='street',
            field=models.CharField(blank=True, max_length=200, verbose_name='street'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_description',
            field=models.CharField(blank=True, max_length=200, verbose_name='user description'),
        ),
        migrations.AddField(
            model_name='user',
            name='zip',
            field=models.CharField(blank=True, max_length=8, verbose_name='zip'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=200, unique=True, verbose_name='username'),
        ),
    ]
