# Generated by Django 3.0.2 on 2021-04-30 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200825_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='final_project',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
