# Generated by Django 3.0.2 on 2021-05-04 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_is_booklet_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=False, help_text='Permission needed to administrate other users in Jobtracker', verbose_name='is admin'),
        ),
    ]
