name: backend

dependencies:
  - python=3.8.13
  - pip=21.0
  - psycopg2=2.8.6
  - pip:
    - Django==3.0.2
    - djangorestframework==3.11.0
    - djangorestframework_simplejwt==4.6.0
    - flake8==3.9.1
    - coreapi==2.3.3
    - Pillow==8.2.0
    - django-cors-headers==3.7.0
    - django-admin-honeypot==1.1.0
    - django-extensions==3.1.3
    - celery==5.0.5
    - redis==3.5.3
    - flower==0.9.5
    - django-celery-results==2.0.1
    - webpreview==1.6.0
    - sentry-sdk==0.14.1
    - weasyprint==52.5
    - django-weasyprint==1.1.0
