# Generated by Django 3.0.2 on 2020-08-27 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0002_auto_20200120_1800'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='email',
            options={'get_latest_by': 'modified'},
        ),
    ]
