# Generated by Django 3.0.2 on 2020-01-23 14:16

from django.db import migrations


def populate_db(apps, schema_editor):
    # Email Types
    email_types = [
        {
            "key": "registration_email",
            "subject": "Thank you for registering!",
            "title": "Thank you for registering!",
            "template": "Click <a href='{{ base_url }}registration-validation?code={{code}}&email={{email_to}}'> here</a> to finalize registration.",
        },
        {
            "key": "password_reset_email",
            "subject": "Password reset",
            "title": "Password reset",
            "template": "Click <a href='{{ base_url }}password-reset-validation?code={{code}}&email={{email_to}}'>  here</a> to reset your password."
        },
        {
            "key": "admin_invite",
            "subject": "You have been invited to Job Tracker",
            "title": "You have been invited to Job Tracker",
            "template": "{{email}} has invited you to his/her job board! You can now access his/her job board in <a href='{{ base_url }}adminboard'> your admin section</a>.<br/><br/>If you haven't heard about Job Tracker yet, you can check it out under <a href='{{ base_url }}'>{{base_url}}</a>."
        },
        {
            "key": "notify_admins_accepted_job",
            "subject": "A user you administer has found a job!",
            "title": "A user you administer has found a job!",
            "template": "{{user_email}} has found a job!"
        },
    ]
    EmailType = apps.get_model('emails', 'EmailType')
    for email_type in email_types:
        EmailType(**email_type).save()


class Migration(migrations.Migration):
    dependencies = [
        ('emails', '0003_auto_20200827_1108'),
    ]

    operations = [
        migrations.RunPython(populate_db),
    ]
