# Generated by Django 3.0.2 on 2020-08-27 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_registrationprofile_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registrationprofile',
            options={'get_latest_by': 'modified'},
        ),
    ]
