# Generated by Django 2.2.2 on 2019-11-14 13:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='uuid')),
                ('index', models.IntegerField(verbose_name='index')),
                ('title', models.TextField(blank=True, verbose_name='job title')),
                ('description', models.TextField(blank=True, verbose_name='job description')),
                ('image', models.ImageField(blank=True, upload_to='', verbose_name='scarepd image')),
                ('company', models.TextField(blank=True, verbose_name='company')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('status', models.CharField(choices=[('WH', 'Wishlist'), ('AP', 'Applied'), ('IN', 'Interviewing'), ('OF', 'Offered')], default='WH', max_length=2, verbose_name='status')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'unique_together': {('index', 'status', 'user')},
            },
        ),
    ]
