# Generated by Django 2.2.2 on 2019-12-17 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_admininvite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admininvite',
            name='email',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invites', to='emails.Email', verbose_name='sent email invite'),
        ),
    ]
