# Generated by Django 2.2.2 on 2019-12-18 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_auto_20191217_0850'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='category',
            field=models.CharField(choices=[('FI', 'Finance'), ('IT', 'Information Technology'), ('ED', 'Education'), ('BU', 'Business'), ('MK', 'Marketing'), ('HE', 'Health'), ('OT', 'Others')], default='OT', max_length=2, verbose_name='categories'),
        ),
    ]
