# Generated by Django 2.2.2 on 2019-12-18 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_job_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='category',
            field=models.CharField(choices=[('Finance', 'Finance'), ('Information Technology', 'Information Technology'), ('Education and Training', 'Education'), ('Business Administration', 'Business'), ('Marketing and Sales', 'Marketing'), ('Health Science', 'Health'), ('Others', 'Others')], default='OT', max_length=100, verbose_name='categories'),
        ),
    ]
