# Generated by Django 3.0.2 on 2020-02-21 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0012_job_cv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='cvs/', verbose_name='cv'),
        ),
    ]
