# Generated by Django 3.0.2 on 2020-02-21 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0013_auto_20200221_1445'),
        ('jobs', '0013_auto_20200221_1434'),
    ]

    operations = [
    ]
