# Generated by Django 3.0.2 on 2020-03-04 10:47

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs', '0014_merge_20200221_1453'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='job',
            unique_together={('id', 'index', 'status', 'user')},
        ),
    ]
