# Generated by Django 3.0.2 on 2020-08-31 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0016_auto_20200825_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='url',
            field=models.CharField(blank=True, max_length=10000, verbose_name='url'),
        ),
    ]
