# Generated by Django 3.0.2 on 2020-08-25 13:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='uuid')),
                ('tag', models.CharField(max_length=32, verbose_name='skill tag')),
                ('level', models.CharField(choices=[('BA', 'Basic'), ('IM', 'Intermediate'), ('PR', 'Proficient')], default='PR', max_length=2, verbose_name='level')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='skills', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='uuid')),
                ('tag', models.CharField(max_length=32, verbose_name='skill tag')),
                ('level', models.CharField(choices=[('BA', 'Basic'), ('IM', 'Intermediate'), ('PR', 'Proficient'), ('NA', 'Native')], default='PR', max_length=2, verbose_name='level')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='languages', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='uuid')),
                ('job_title', models.CharField(blank=True, max_length=50, verbose_name='job title')),
                ('employer', models.CharField(blank=True, max_length=50, verbose_name='employer')),
                ('city', models.CharField(blank=True, max_length=50, verbose_name='city')),
                ('country', models.CharField(blank=True, max_length=50, verbose_name='country')),
                ('start_date', models.DateField(null=True, verbose_name='start date')),
                ('end_date', models.DateField(null=True, verbose_name='end date')),
                ('description', models.CharField(blank=True, max_length=400, verbose_name='job description')),
                ('webpage', models.URLField(blank=True, null=True, verbose_name='employer web page')),
                ('contact', models.CharField(blank=True, max_length=200, verbose_name='reference contact')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='uuid')),
                ('education_title', models.CharField(blank=True, max_length=50, verbose_name='education title')),
                ('institute', models.CharField(blank=True, max_length=50, verbose_name='education institute')),
                ('city', models.CharField(blank=True, max_length=50, verbose_name='city')),
                ('country', models.CharField(blank=True, max_length=50, verbose_name='country')),
                ('start_date', models.DateField(null=True, verbose_name='start date')),
                ('end_date', models.DateField(null=True, verbose_name='end date')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='education description')),
                ('webpage', models.URLField(blank=True, null=True, verbose_name='education web page')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
    ]
