# Generated by Django 3.0.2 on 2020-01-20 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notificationprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationtype',
            name='key',
            field=models.CharField(max_length=200, unique=True, verbose_name='notification key'),
        ),
    ]
