# Generated by Django 3.0.2 on 2020-04-22 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='name')),
                ('email', models.CharField(default=False, max_length=300, verbose_name='email')),
                ('comments', models.TextField(default=False, max_length=500, verbose_name='comments')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
            ],
        ),
    ]
