# Generated by Django 3.0.2 on 2020-04-22 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='name',
        ),
        migrations.AddField(
            model_name='contact',
            name='user_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='user name'),
        ),
    ]
